conversion.h File Reference
Data Structures
struct ueacval
Defines
#define V_CONVERSION 0
#define I_CONVERSION 1
Typedefs
typedef ueacval ueacval_t
Functions
void convert_a2d (char, unsigned short, ueacval_t *, int)
Define Documentation
#define I_CONVERSION 1
Definition at line 53 of file conversion.h.
Referenced by current_output_calibration(), evaluate_lla(), print_grid_i(), scan_probes(), and ueac_execute_instruction().
#define V_CONVERSION 0
Definition at line 52 of file conversion.h.
Referenced by convert_a2d(), print_grid_v(), and ueac_execute_instruction().
Typedef Documentation
typedef struct ueacval ueacval_t
Function Documentation
void convert_a2d (char, unsigned short, ueacval_t *, int)
Definition at line 61 of file conversion.c.
References a2d_i_conversion, ueacval::hundredth, cal::i_in_floor, cal::i_in_offset, ueacval::integer, ueac::pin_cal, ueac_state, and V_CONVERSION.
Referenced by current_output_calibration(), evaluate_lla(), print_grid_i(), print_grid_v(), scan_probes(), and ueac_execute_instruction().
61                                                                                         {
62   if (value_type==V_CONVERSION) {
63     if (a2d_data < 400) {
64       return_val->integer=0;
65       return_val->hundredth=a2d_data>>2;
66     }
67     else if (a2d_data < 800) {
68       return_val->integer=1;
69       return_val->hundredth=(a2d_data-400)>>2;
70     }
71     else if (a2d_data < 1200) {
72       return_val->integer=2;
73       return_val->hundredth=(a2d_data-800)>>2;
74     }
75     else if (a2d_data < 1600) {
76       return_val->integer=3;
77       return_val->hundredth=(a2d_data-1200)>>2;
78     }
79     else if (a2d_data < 2000) {
80       return_val->integer=4;
81       return_val->hundredth=(a2d_data-1600)>>2;
82     }
83     else if (a2d_data < 2400) {
84       return_val->integer=5;
85       return_val->hundredth=(a2d_data-2000)>>2;
86     }
87     else if (a2d_data < 2800) {
88       return_val->integer=6;
89       return_val->hundredth=(a2d_data-2400)>>2;
90     }
91     else if (a2d_data < 3200) {
92       return_val->integer=7;
93       return_val->hundredth=(a2d_data-2800)>>2;
94     }
95     else if (a2d_data < 3600) {
96       return_val->integer=8;
97       return_val->hundredth=(a2d_data-3200)>>2;
98     }
99     else if (a2d_data < 4000) {
100       return_val->integer=9;
101       return_val->hundredth=(a2d_data-3600)>>2;
102     }
103     else {
104       return_val->integer=10;
105       return_val->hundredth=(a2d_data-4000)>>2;
106     }
107   }
108   else {
109     return_val->integer=a2d_i_conversion[a2d_data];
110     if (pin<25) {
111       if (return_val->integer<=ueac_state.pin_cal[pin].i_in_floor) {
112         return_val->integer=0;
113       }
114       else {
115         return_val->integer+=ueac_state.pin_cal[pin].i_in_offset;
116       }
117     }
118     return_val->hundredth=0;
119   }
120 }