external_flash.h File Reference
Defines
#define nCS_LOW {P4OUT &= ~BIT3;}
#define nCS_HIGH {P4OUT |= BIT3;}
#define PAGE_SIZE 264
#define NUMBER_PAGES 1024
Functions
int flash_integrity_test (void)
unsigned char send_spi_byte (unsigned char)
void init_spi (void)
void start_main_array_read (unsigned short, unsigned short)
void end_main_array_read (void)
void page_to_buffer1_compare (unsigned short)
void buffer1_to_page_e (unsigned short)
void buffer2_to_page_e (unsigned short)
unsigned char poll_status_register_blocking (void)
void buffer1_write (unsigned short, unsigned char)
void buffer2_write (unsigned short, unsigned char)
unsigned char buffer1_read (unsigned short)
unsigned char buffer2_read (unsigned short)
Define Documentation
#define nCS_HIGH {P4OUT |= BIT3;}
Definition at line 60 of file external_flash.h.
Referenced by buffer1_read(), buffer1_to_page_e(), buffer1_write(), buffer2_read(), buffer2_to_page_e(), buffer2_write(), end_main_array_read(), page_to_buffer1_compare(), and poll_status_register_blocking().
#define nCS_LOW {P4OUT &= ~BIT3;}
Definition at line 59 of file external_flash.h.
Referenced by buffer1_read(), buffer1_to_page_e(), buffer1_write(), buffer2_read(), buffer2_to_page_e(), buffer2_write(), page_to_buffer1_compare(), poll_status_register_blocking(), and start_main_array_read().
#define NUMBER_PAGES 1024
Definition at line 62 of file external_flash.h.
#define PAGE_SIZE 264
Definition at line 61 of file external_flash.h.
Referenced by current_output_calibration(), and flash_integrity_test().
Function Documentation
unsigned char buffer1_read (unsigned short)
Definition at line 244 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
Referenced by flash_integrity_test().
244                                                 {
245   unsigned char temp;
246   nCS_LOW;
247   send_spi_byte(0xD4);       // command for byte write to buff 1
248   send_spi_byte(0x00);       // dummy byte
249   if (addr>0xFF) {
250     send_spi_byte(0x01);     // MSB of buffer address
251   }
252   else {
253     send_spi_byte(0x00);     // MSB of buffer address
254   }  
255   send_spi_byte((unsigned char) addr); // send the balance of the address
256   send_spi_byte(0x00);       // extra clocks required by the flash
257   temp=send_spi_byte(0x00);  // this is the data 
258   nCS_HIGH; 
259   return(temp);
260 }
void buffer1_to_page_e (unsigned short)
Definition at line 177 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
Referenced by current_output_calibration().
177                                             {
178   unsigned char page_temp;
179   nCS_LOW;
180   send_spi_byte(0x83);       // 0x83 command for byte write to buff 1
181   page_temp = (unsigned char)(page>>7);
182   send_spi_byte (page_temp);
183   page_temp = (unsigned char) (page<<1);
184   send_spi_byte (page_temp);
185   send_spi_byte (0x00);
186   nCS_HIGH;                 // starts the page erase and program 
187 }
void buffer1_write (unsigned short, unsigned char)
Definition at line 214 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
Referenced by current_output_calibration(), and flash_integrity_test().
214                                                                  {
215   nCS_LOW;
216   send_spi_byte(0x84);       // command for byte write to buff 1
217   send_spi_byte(0x00);       // dummy byte
218   if (addr>0xFF) {
219     send_spi_byte(0x01);     // dummy byte except 
220   }
221   else {
222     send_spi_byte(0x00);     // dummy byte except 
223   }  
224   send_spi_byte((unsigned char) addr); // send the balance of the address
225   send_spi_byte(data_byte);
226   nCS_HIGH; 
227 }
unsigned char buffer2_read (unsigned short)
Definition at line 262 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
Referenced by flash_integrity_test().
262                                                 {
263   unsigned char temp;
264   nCS_LOW;
265   send_spi_byte(0xD6);       // command for byte write to buff 1
266   send_spi_byte(0x00);       // dummy byte
267   if (addr>0xFF) {
268     send_spi_byte(0x01);     // MSB of buffer address
269   }
270   else {
271     send_spi_byte(0x00);     // MSB of buffer address
272   }  
273   send_spi_byte((unsigned char) addr); // send the balance of the address
274   send_spi_byte(0x00);       // extra clocks required by the flash
275   temp=send_spi_byte(0x00);  // this is the data 
276   nCS_HIGH; 
277   return(temp);
278 }
void buffer2_to_page_e (unsigned short)
Definition at line 189 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
189                                             {
190   unsigned char page_temp;
191   nCS_LOW;
192   send_spi_byte(0x86);       // 0x86 command for byte write to buff 2
193   page_temp = (unsigned char)(page>>7);
194   send_spi_byte (page_temp);
195   page_temp = (unsigned char) (page<<1);
196   send_spi_byte (page_temp);
197   send_spi_byte (0x00);
198   nCS_HIGH;                 // starts the page erase and program 
199 }
void buffer2_write (unsigned short, unsigned char)
Definition at line 229 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
Referenced by flash_integrity_test().
229                                                                  {
230   nCS_LOW;
231   send_spi_byte(0x87);       // command for byte write to buff 2
232   send_spi_byte(0x00);       // dummy byte
233   if (addr>0xFF) {
234     send_spi_byte(0x01);     // dummy byte except 
235   }
236   else {
237     send_spi_byte(0x00);     // dummy byte except 
238   }  
239   send_spi_byte((unsigned char) addr); // send the balance of the address
240   send_spi_byte(data_byte);
241   nCS_HIGH; 
242 }
void end_main_array_read (void)
Definition at line 161 of file external_flash.c.
References nCS_HIGH.
Referenced by init_ueac_state_structure().
161                                {
162   nCS_HIGH;
163 }
int flash_integrity_test (void)
Definition at line 53 of file external_flash.c.
References BLACK, buffer1_read(), buffer1_write(), buffer2_read(), buffer2_write(), GREEN, PAGE_SIZE, and RED.
Referenced by main().
53                                {
54   enum {PASS,FAIL};
55   int i,fail_flag; 
56   unsigned char data=0;
57   // unsigned short page=0;
58   // printf("### Flash Tests ###\n\r");
59   // SRAM BUFFER 1
60 
61   //  poll_status_register_blocking();                  // Wait for the flash page erase/write to complete 
62   fail_flag=PASS;
63   data=0;
64 
65   for (i=0;i<PAGE_SIZE;i++) {
66     buffer1_write((unsigned short)i,data++);         // SRAM Buffer 1 Fill 
67   }
68   data=0;
69   for (i=0;i<PAGE_SIZE;i++) {
70     if (data++!=buffer1_read(i)) {
71       fail_flag=FAIL;
72     }
73   }
74   printf("External Flash SRAM Buffer 1 Fill ");
75   if (fail_flag==FAIL) {
76     printf(RED);
77     printf("[FAILED]\n\r");
78   }
79   else {
80     printf(GREEN);
81     printf("[PASSED]\n\r");
82   }
83   printf(BLACK);
84 
85   // BUFFER 2
86   fail_flag=PASS;
87   data=0;
88   for (i=0;i<PAGE_SIZE;i++) {
89     buffer2_write((unsigned short)i,data++);         // SRAM Buffer 1 Fill 
90   }
91   data=0;
92   for (i=0;i<PAGE_SIZE;i++) {
93     if (data++!=buffer2_read(i)) {
94       fail_flag=FAIL;
95     }
96   }
97   printf("External Flash SRAM Buffer 2 Fill ");
98   if (fail_flag==FAIL) {
99     printf(RED);
100     printf("[FAILED]\n\r");
101   }
102   else {
103     printf(GREEN);
104     printf("[PASSED]\n\r");
105   }
106   printf(BLACK);
107   
108   // FLASH PAGES
109 /*   fail_flag=PASS; */
110 /*   printf("External Flash Array Write \r"); */
111 /*   for (page=0;page<NUMBER_PAGES;page++){ */
112 /*     printf("External Flash Array Write %d\r",page); */
113 /*     buffer1_to_page_e(page); */
114 /*     poll_status_register_blocking();                  // Wait for the flash page erase/write to complete */
115 /*     start_main_array_read(page,0); */
116 /*     data=0; */
117 /*     for (i=0;i<PAGE_SIZE;i++) { */
118 /*       if (data++!=send_spi_byte(0)) { */
119 /*         fail_flag=FAIL; */
120 /*       } */
121 /*     } */
122 /*     end_main_array_read(); */
123 /*   } */
124 /*   printf("External Flash Array Write "); */
125 /*   if (fail_flag==FAIL) { */
126 /*     printf(RED); */
127 /*     printf("[FAILED]\n\r"); */
128 /*   } */
129 /*   else { */
130 /*     printf(GREEN); */
131 /*     printf("[PASSED]\n\r"); */
132 /*   } */
133 /*   printf(BLACK); */
134   return (0);
135 }
void init_spi (void)
void page_to_buffer1_compare (unsigned short)
Definition at line 165 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
165                                                   {
166   unsigned char page_temp;
167   nCS_LOW;
168   send_spi_byte(0x60);           // command for byte write to buff 1
169   page_temp = (unsigned char)(page>>7);
170   send_spi_byte (page_temp);
171   page_temp = (unsigned char) (page<<1);
172   send_spi_byte (page_temp);
173   send_spi_byte (0x00);
174   nCS_HIGH;
175 }
unsigned char poll_status_register_blocking (void)
Definition at line 201 of file external_flash.c.
References nCS_HIGH, nCS_LOW, and send_spi_byte().
201                                                   {  
202   unsigned char status;
203   status = 0;
204   nCS_LOW;  
205   //  send_spi_byte(0x57);
206   send_spi_byte(0xD7);
207   while (!(status&0x80)) { 
208     status = send_spi_byte(0x00); // send data to get the spi to clock
209   }
210   nCS_HIGH;
211   return (status); 
212 }
unsigned char send_spi_byte (unsigned char)
Definition at line 154 of file ueaclib.c.
Referenced by buffer1_read(), buffer1_to_page_e(), buffer1_write(), buffer2_read(), buffer2_to_page_e(), buffer2_write(), init_ueac_state_structure(), page_to_buffer1_compare(), poll_status_register_blocking(), start_main_array_read(), and write_dac().
154                                                      {
155   TXBUF0 = data_byte;        // buffer 1 write  
156   while(!(UTCTL0&0x01));     // wait until transmitter empty
157   return(RXBUF0);            // return any received data
158                              // No data returned from DAC
159                              // SPI flash returns read data
160 }
void start_main_array_read (unsigned short, unsigned short)
Definition at line 137 of file external_flash.c.
References nCS_LOW, and send_spi_byte().
Referenced by init_ueac_state_structure().
137                                                                     {
138   unsigned char page_temp; 
139 
140   nCS_LOW;
141   // opcode
142   send_spi_byte(0xE8);  // SPI Mode 0 or 3  
143 
144   // Prepare/send the page and address fields
145   page_temp = (unsigned char)(page>>7);
146   send_spi_byte (page_temp);
147   page_temp = (unsigned char) (page<<1);
148   if (addr>0xff) {
149     page_temp |=0x01;
150   }
151   send_spi_byte (page_temp);
152   send_spi_byte ((unsigned char) addr);
153 
154   // additional bytes
155   send_spi_byte(0x00);
156   send_spi_byte(0x00);
157   send_spi_byte(0x00);
158   send_spi_byte(0x00);
159 }