lla.c File Reference
#include <stdio.h>
#include `ueaclib.h`
#include `ueac.h`
#include `lla.h`
#include `conversion.h`
#include `filter.h`
#include `global.h`
Defines
#define INSTR ueac_state $\rightarrow$ instruction
#define LLA_TABLE ueac_state $\rightarrow$ lla_table
#define DISABLE 0
#define ENABLE 1
#define UNINITIALIZED 0xFF
Functions
int lla_report (ueac_t *ueac_state, lla_data_t *lla_data)
int lla_add (ueac_t *ueac_state)
int lla_disable (ueac_t *ueac_state)
int lla_enable (ueac_t *ueac_state)
int evaluate_lla (ueac_t *ueac_state)
void lla_print_active (ueac_t *ueac_state)
Define Documentation
#define DISABLE 0
Definition at line 60 of file lla.c.
Referenced by lla_add(), lla_disable(), and lla_enable().
#define ENABLE 1
Definition at line 61 of file lla.c.
Referenced by evaluate_lla(), lla_add(), lla_disable(), lla_enable(), lla_print_active(), and lla_report().
#define INSTR ueac_state $\rightarrow$ instruction
Definition at line 57 of file lla.c.
Referenced by lla_add(), lla_disable(), lla_enable(), and lla_report().
#define LLA_TABLE ueac_state $\rightarrow$ lla_table
Definition at line 58 of file lla.c.
#define UNINITIALIZED 0xFF
Definition at line 62 of file lla.c.
Function Documentation
int evaluate_lla (ueac_t * ueac_state)
Definition at line 134 of file lla.c.
References convert_a2d(), ENABLE, I_CONVERSION, ueacval::integer, LLA_TABLE, pin_data, and write_current().
Referenced by timer_a0_irq().
134                                      {
135   ueacval_t result;
136   static unsigned char count=0;
137   if (++count>9) {
138     count=0;
139   }
140   if (LLA_TABLE[count].enable==ENABLE) {
141 #ifndef LINUX
142     convert_a2d(I_CONVERSION,pin_data[LLA_TABLE[count].in_pin].filtered_result,&result,LLA_TABLE[count].in_pin);
143 #else 
144     convert_a2d(I_CONVERSION,0,&result,25);
145 #endif
146     LLA_TABLE[count].in_val=result.integer;      
147     if (++LLA_TABLE[count].counter>=LLA_TABLE[count].period) {
148       LLA_TABLE[count].counter=0;
149       LLA_TABLE[count].accumulator+=LLA_TABLE[count].in_val;
150       LLA_TABLE[count].in_val=(int)(LLA_TABLE[count].accumulator/LLA_TABLE[count].period);
151       if (LLA_TABLE[count].in_val>200) {
152         LLA_TABLE[count].out_val=*(LLA_TABLE[count].function_ptr+200);
153       }
154       else {
155         LLA_TABLE[count].out_val=*(LLA_TABLE[count].function_ptr+LLA_TABLE[count].in_val);
156       }
157       if (LLA_TABLE[count].out_pin!=0xFF) {
158 #ifndef LINUX
159         write_current(LLA_TABLE[count].out_pin,LLA_TABLE[count].out_val);
160 #endif
161       }
162       LLA_TABLE[count].accumulator=0;
163     }
164     else {
165       LLA_TABLE[count].accumulator+=LLA_TABLE[count].in_val;
166     }
167   }
168   return (0);
169 }
int lla_add (ueac_t * ueac_state)
Definition at line 76 of file lla.c.
References DISABLE, ENABLE, INSTR, lla_function_index, ueac::lla_input, LLA_TABLE, and write_lla().
Referenced by ueac_execute_instruction().
76                                  {
77   int index;
78   index=INSTR.lla_descriptor-1;
79   LLA_TABLE[index].enable=DISABLE;
80   LLA_TABLE[index].in_pin=(INSTR.pin_y-1)*5+(INSTR.pin_x-1);
81   if ((INSTR.pin_x_alt==0)||(INSTR.pin_y_alt==0)) {
82     LLA_TABLE[index].out_pin=0xFF;
83   }
84   else {
85     LLA_TABLE[index].out_pin=(INSTR.pin_y_alt-1)*5+(INSTR.pin_x_alt-1);
86   }
87   LLA_TABLE[index].function_ptr=(int *)lla_function_index[INSTR.lla_function-1];
88   LLA_TABLE[index].period=INSTR.lla_period;
89   LLA_TABLE[index].accumulator=0;
90   ueac_state->lla_input|=(unsigned long)(0x00000001<<LLA_TABLE[index].in_pin);
91 #ifndef LINUX 
92   write_lla(LLA_TABLE[index].in_pin,1);
93 #endif 
94   LLA_TABLE[index].in_val=0;
95   LLA_TABLE[index].out_val=0;
96   LLA_TABLE[index].enable=ENABLE;
97   return 0;
98 }
int lla_disable (ueac_t * ueac_state)
Definition at line 100 of file lla.c.
References DISABLE, ENABLE, INSTR, ueac::lla_input, LLA_TABLE, write_current(), and write_lla().
Referenced by ueac_execute_instruction().
100                                      {
101   int index;
102   int ret_val=-1;
103   index=INSTR.lla_descriptor-1;
104   if (LLA_TABLE[index].enable==ENABLE) {
105     ueac_state->lla_input&=~((unsigned long)(0x00000001<<LLA_TABLE[index].in_pin));
106     LLA_TABLE[index].enable=DISABLE;
107 #ifndef LINUX    
108     write_lla(LLA_TABLE[index].in_pin,0);
109     write_current(LLA_TABLE[index].out_pin,0);
110 #endif 
111     ret_val=0;
112   }
113   return(ret_val);
114 }
int lla_enable (ueac_t * ueac_state)
Definition at line 116 of file lla.c.
References DISABLE, ENABLE, INSTR, ueac::lla_input, LLA_TABLE, write_current(), and write_lla().
Referenced by ueac_execute_instruction().
116                                     {
117   int index;
118   int ret_val=-1;
119   index=INSTR.lla_descriptor-1;
120   if (LLA_TABLE[index].enable==DISABLE) {
121     ueac_state->lla_input|=(unsigned long)(0x00000001<<LLA_TABLE[index].in_pin);
122 #ifndef LINUX
123     write_lla(LLA_TABLE[index].in_pin,1);
124     write_current(LLA_TABLE[index].out_pin,0);
125 #endif 
126     LLA_TABLE[index].in_val=0;
127     LLA_TABLE[index].out_val=0;
128     LLA_TABLE[index].enable=ENABLE;
129     ret_val=0;
130   }
131   return(ret_val);
132 }
void lla_print_active (ueac_t * ueac_state)
Definition at line 171 of file lla.c.
References ENABLE, ueac::lla_input, and LLA_TABLE.
171                                            {
172   int i;
173   printf ("lla_input var=0x%08lx\n",ueac_state->lla_input);
174   for (i=0;i<10;i++) {
175 #ifdef LINUX
176     printf("\nLLA %d\n",i+1);
177     if (LLA_TABLE[i].enable==ENABLE) {
178       printf("enable state=ENABLED\n");
179       printf("input pin = %d\n",LLA_TABLE[i].in_pin);
180       printf("output pin = %d\n",LLA_TABLE[i].out_pin);
181       printf("first data val = %d\n",*(LLA_TABLE[i].function_ptr+100));
182       printf("period = %d\n",LLA_TABLE[i].period);
183       printf("in_val = %d\n",LLA_TABLE[i].in_val);
184       printf("out_val = %d\n",LLA_TABLE[i].out_val);
185       printf("accumulator = %ld\n",LLA_TABLE[i].accumulator);
186     }
187     else {
188       printf("enable state=DISABLED\n");
189     }
190 #else 
191     printf("\nLLA %d\n\r",i+1);
192     if (LLA_TABLE[i].enable==ENABLE) {
193       printf("enable state=ENABLED\n\r");
194       printf("input pin = %d\n\r",LLA_TABLE[i].in_pin);
195       printf("output pin = %d\n\r",LLA_TABLE[i].out_pin);
196       printf("first data val = %d\n\r",*(LLA_TABLE[i].function_ptr+100));
197       printf("period = %d\n\r",LLA_TABLE[i].period);
198       printf("in_val = %d\n\r",LLA_TABLE[i].in_val);
199       printf("out_val = %d\n\r",LLA_TABLE[i].out_val);
200       printf("accumulator = %ld\n\r",LLA_TABLE[i].accumulator);
201     }
202     else {
203       printf("enable state=DISABLED\n");
204     }
205 #endif
206 
207   }
208 }
int lla_report (ueac_t * ueac_state, lla_data_t * lla_data)
Definition at line 64 of file lla.c.
References ENABLE, lla_data::input, INSTR, LLA_TABLE, and lla_data::output.
Referenced by ueac_execute_instruction().
64                                                          {
65   int index;
66   int ret_val=-1;
67   index=INSTR.lla_descriptor-1;
68   if (LLA_TABLE[index].enable==ENABLE) {
69     lla_data->input=LLA_TABLE[index].in_val;
70     lla_data->output=LLA_TABLE[index].out_val;
71     ret_val=0;
72   }
73   return ret_val;
74 }