main.c File Reference
#include <msp430x16x.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include `ueaclib.h`
#include `ueac.h`
#include `external_flash.h`
#include `interpreter.h`
#include `filter.h`
#include `conversion.h`
#include `global.h`
#include `timer.h`
#include `calibrate.h`
Functions
void print_grid_v ()
void print_grid_i ()
int get_command (char *command_buf)
int main (void)
void scan_probes ()
Variables
short dac_translation []
Function Documentation
int get_command (char * command_buf)
Definition at line 129 of file main.c.
References getchar().
Referenced by main().
129                                    {
130   char ch;
131   int counter=0;
132   while(((ch=getchar())!='\n')&&(ch!='\r')&&(counter++<100)) {
133     *command_buf++=ch;
134   }
135   *command_buf++='\n';
136   *command_buf=0;
137   return (counter);
138 }     
int main (void)
Definition at line 88 of file main.c.
References BACK_WHITE, CLR, command, delay_1_25mS(), flash_integrity_test(), get_command(), init_global_variables(), init_sys(), interpreter(), led_screen_enable, scan_leds(), ueac_state, write_current(), write_led(), and write_lla().
88                {
89   int i;
90   init_sys();                        // setup the MSP430 peripherals
91   printf(BACK_WHITE);
92   printf(CLR);
93   printf("UEAC POST\n\r");
94   flash_integrity_test();
95   scan_leds();
96   init_global_variables();
97   for (i=0;i<25;i++) {
98     write_lla(i,0);
99     write_led(i,0);
100     write_current(i,0);
101   }
102   delay_1_25mS(800);     
103   printf(CLR);
104   printf("uEACos V2.2 base_002.9\n\r");
105   led_screen_enable=1;
106   while(1) {
107     printf("ueac> ");
108     get_command(command);
109     interpreter(command,&ueac_state);
110   }
111 }
void print_grid_i ()
Definition at line 151 of file main.c.
References conversion_result, convert_a2d(), delay_1_25mS(), I_CONVERSION, ueacval::integer, pin_data, write_current(), and write_lla().
151                     {
152   int i,j;
153   for (i=0;i<5;i++) {
154     for (j=0;j<5;j++) {
155       write_lla(i*5+j,1);
156       write_current(i*5+j,200);
157       delay_1_25mS(500);
158       convert_a2d(I_CONVERSION,pin_data[i*5+j].filtered_result,&conversion_result,i*5+j); 
159       printf("%d ",conversion_result.integer);
160       write_lla(i*5+j,0);
161     }
162     printf("\n\r");
163   }
164 }
void print_grid_v ()
Definition at line 140 of file main.c.
References conversion_result, convert_a2d(), ueacval::hundredth, ueacval::integer, pin_data, and V_CONVERSION.
140                     {
141   int i,j;
142   for (i=0;i<5;i++) {
143     for (j=0;j<5;j++) {
144       convert_a2d(V_CONVERSION,pin_data[i*5+j].filtered_result,&conversion_result,i*5+j); 
145       printf("%d.%d ",conversion_result.integer,conversion_result.hundredth);
146     }
147     printf("\n\r");
148   }
149 }
void scan_probes ()
Definition at line 113 of file main.c.
References conversion_result, convert_a2d(), delay_1_25mS(), I_CONVERSION, ueacval::integer, pin_data, write_current(), and write_lla().
113                    {
114   int i,j;
115   for (i=0;i<25;i++) {
116     write_lla(i,1);
117     printf("%d ",i);
118     for (j=200;j>=0;j-=50) {
119       write_current(i,j);
120       delay_1_25mS(400);     
121       convert_a2d(I_CONVERSION,pin_data[i].filtered_result,&conversion_result,i);
122       printf("%d ",conversion_result.integer);
123     }
124     printf("\n\r");
125     write_lla(i,0);
126   }
127 }
Variable Documentation
short dac_translation[]
Definition at line 45 of file cal_table.h.