timer.h File Reference
Functions
void delay_1_25mS (int count)
Function Documentation
void delay_1_25mS (int count)
Definition at line 116 of file timer.c.
References timer_tick.
Referenced by current_output_calibration(), main(), print_grid_i(), scan_leds(), and scan_probes().
116                              {
117   int tick_counter=0;
118   while (tick_counter<count) {
119     if (timer_tick) {
120       tick_counter++;
121       timer_tick=0;
122     }
123   }
124 }