timer.c File Reference
#include <msp430x16x.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include `ueaclib.h`
#include `ueac.h`
#include `conversion.h`
#include `filter.h`
#include `global.h`
#include `lla.h`
Functions
timer_a0_irq ()
void delay_1_25mS (int count)
Function Documentation
void delay_1_25mS (int count)
Definition at line 116 of file timer.c.
References timer_tick.
Referenced by current_output_calibration(), main(), print_grid_i(), scan_leds(), and scan_probes().
116                              {
117   int tick_counter=0;
118   while (tick_counter<count) {
119     if (timer_tick) {
120       tick_counter++;
121       timer_tick=0;
122     }
123   }
124 }
timer_a0_irq ()
Timer A1 Interupt Handler
Timer A is used as the time base for the scheduler. This interrupt occurs every 1.25mS.
Definition at line 66 of file timer.c.
References evaluate_lla(), high_time_limit, led_pwm(), led_screen_enable, lla_input_check(), pin_data, start_a2d_converter(), timer_tick, ueac_state, update_a2d_data(), and write_analog_mux().
66                {
67   static int chan_last=0;
68   static int chan_next=0;
69   static char state=0;
70 
71   TACCR0+=0x900;               // Increment the compare register for 2305 ticks into future (625uS)
72   if (!state) {                // evaluate the system every 1.25mS 
73     chan_last=chan_next&0x07;
74     write_analog_mux(++chan_next);
75 
76     update_a2d_data(&pin_data[chan_last],ADC12MEM0);
77     update_a2d_data(&pin_data[8+chan_last],ADC12MEM1);
78     update_a2d_data(&pin_data[16+chan_last],ADC12MEM2);
79     if (chan_last==0) {
80       update_a2d_data(&pin_data[24],ADC12MEM3);
81     }
82 
83     if (lla_input_check(chan_last,&ueac_state)) {
84       high_time_limit[chan_last]=1;
85     }
86     else {
87       high_time_limit[chan_last]=ADC12MEM0>>8;
88     }
89     if (lla_input_check(8+chan_last,&ueac_state)) {
90       high_time_limit[8+chan_last]=1;
91     }
92     else {
93       high_time_limit[8+chan_last]=ADC12MEM1>>8;
94     }
95     if (lla_input_check(16+chan_last,&ueac_state)) {
96       high_time_limit[16+chan_last]=1;
97     }
98     else {
99       high_time_limit[16+chan_last]=ADC12MEM2>>8;
100     }
101 
102     if (lla_input_check(24,&ueac_state)) {
103       high_time_limit[24]=2;
104     }
105     else {
106       high_time_limit[24]=(ADC12MEM3>>8)+1;
107     }
108     evaluate_lla(&ueac_state);
109     start_a2d_converter();
110     timer_tick=1;
111   }
112   state^=1;
113   led_pwm(led_screen_enable);
114 }