ueaclib.h File Reference
Defines
#define BLACK `\x1B[30m`
#define RED `\x1B[31m`
#define GREEN `\x1B[32m`
#define BACK_WHITE `\x1B[47m`
#define CLR `\033[2J`
#define TERM_RESET `\033[H`
Functions
void init_sys (void)
int putchar_0 (int)
char getchar_0 (void)
int putchar (int)
char getchar (void)
unsigned char send_spi_byte (unsigned char)
void write_dac (int, int)
void write_current (int, int)
void write_led (int, int)
void write_lla (int, int)
void start_a2d_converter (void)
int wait_a2d_busy (void)
void write_analog_mux (unsigned char)
void system_reset (void)
void led_pwm (int)
void clear_led_screen (void)
Define Documentation
#define BACK_WHITE `\x1B[47m`
Definition at line 68 of file ueaclib.h.
Referenced by main().
#define BLACK `\x1B[30m`
Definition at line 65 of file ueaclib.h.
Referenced by flash_integrity_test(), and scan_leds().
#define CLR `\033[2J`
Definition at line 70 of file ueaclib.h.
Referenced by main().
#define GREEN `\x1B[32m`
Definition at line 67 of file ueaclib.h.
Referenced by flash_integrity_test(), and scan_leds().
#define RED `\x1B[31m`
Definition at line 66 of file ueaclib.h.
Referenced by flash_integrity_test().
#define TERM_RESET `\033[H`
Definition at line 71 of file ueaclib.h.
Function Documentation
void clear_led_screen (void)
Definition at line 489 of file ueaclib.c.
Referenced by ueac_execute_instruction().
489                              {
490   P1OUT=0;
491   P5OUT=0x07;
492   P5OUT=0;
493   P2OUT&=~0x01;
494 }
char getchar (void)
Definition at line 184 of file ueaclib.c.
Referenced by current_output_calibration(), and get_command().
184                    {
185   char rx_data;
186   while (!(IFG2&URXIFG1));
187   rx_data= RXBUF1;
188   return (rx_data);
189 }
char getchar_0 (void)
void init_sys (void)
Definition at line 79 of file ueaclib.c.
References clear_latches(), init_a2d(), init_dac(), init_pins(), init_serial_1(), init_spi_0(), init_timer_a(), and Set_DCO().
Referenced by main().
79                     {
80   unsigned int i;
81   WDTCTL = WDTPW + WDTHOLD;    // Stop watchdog
82   init_pins();                 // Setup the discrete I/O - important to enable 8Mhz crystal 
83   for (i = 0xFFFF;i>0;i--);    // Delay for XTAL and oscillator to fire up and settle
84   Set_DCO();                   // calibrate DCO using the 32.768Khz crystal to 3.686400 Mhz  
85   init_spi_0();
86   init_serial_1();             // initialize USB virtual serial port
87   init_timer_a();              
88   init_dac();
89   init_a2d();
90   clear_latches();
91   _EINT();                     // Global interrupt enable
92 }
void led_pwm (int)
Definition at line 441 of file ueaclib.c.
References high_time_limit, and PWM_COUNT_MASK.
Referenced by timer_a0_irq().
441                           {
442   static unsigned char counter=0;
443   if (enable) {
444     counter++;
445     counter&=PWM_COUNT_MASK; 
446     if (!counter) {
447       P1OUT=0xFF;
448       P5OUT=0x07;
449       P5OUT=0;
450       P2OUT|=0x01;
451     }
452     P1OUT=0xFF;
453     if (counter>=high_time_limit[0]) P1OUT&=~0x01;
454     if (counter>=high_time_limit[1]) P1OUT&=~0x02;
455     if (counter>=high_time_limit[2]) P1OUT&=~0x04;
456     if (counter>=high_time_limit[3]) P1OUT&=~0x08;
457     if (counter>=high_time_limit[4]) P1OUT&=~0x10;
458     if (counter>=high_time_limit[5]) P1OUT&=~0x20;
459     if (counter>=high_time_limit[6]) P1OUT&=~0x40;
460     if (counter>=high_time_limit[7]) P1OUT&=~0x80;
461     P5OUT=0x01;
462     P5OUT=0x00;
463     P1OUT=0xFF;
464     if (counter>=high_time_limit[8]) P1OUT&=~0x01;
465     if (counter>=high_time_limit[9]) P1OUT&=~0x02;
466     if (counter>=high_time_limit[10]) P1OUT&=~0x04;
467     if (counter>=high_time_limit[11]) P1OUT&=~0x08;
468     if (counter>=high_time_limit[12]) P1OUT&=~0x10;
469     if (counter>=high_time_limit[13]) P1OUT&=~0x20;
470     if (counter>=high_time_limit[14]) P1OUT&=~0x40;
471     if (counter>=high_time_limit[15]) P1OUT&=~0x80;
472     P5OUT=0x02;
473     P5OUT=0x00;
474     P1OUT=0xFF;
475     if (counter>=high_time_limit[16]) P1OUT&=~0x01;
476     if (counter>=high_time_limit[17]) P1OUT&=~0x02;
477     if (counter>=high_time_limit[18]) P1OUT&=~0x04;
478     if (counter>=high_time_limit[19]) P1OUT&=~0x08;
479     if (counter>=high_time_limit[20]) P1OUT&=~0x10;
480     if (counter>=high_time_limit[21]) P1OUT&=~0x20;
481     if (counter>=high_time_limit[22]) P1OUT&=~0x40;
482     if (counter>=high_time_limit[23]) P1OUT&=~0x80;
483     P5OUT=0x04;
484     P5OUT=0x00;
485     if (counter>=high_time_limit[24]) P2OUT&=~0x01;
486   }
487 }
int putchar (int)
Definition at line 178 of file ueaclib.c.
178                         {
179   while (!(IFG2&UTXIFG1));
180   TXBUF1=in_char;
181   return(0);
182 }
int putchar_0 (int)
unsigned char send_spi_byte (unsigned char)
Definition at line 154 of file ueaclib.c.
154                                                      {
155   TXBUF0 = data_byte;        // buffer 1 write  
156   while(!(UTCTL0&0x01));     // wait until transmitter empty
157   return(RXBUF0);            // return any received data
158                              // No data returned from DAC
159                              // SPI flash returns read data
160 }
void start_a2d_converter (void)
void system_reset (void)
int wait_a2d_busy (void)
Definition at line 371 of file ueaclib.c.
371                         {
372   int count=0;
373   while (ADC12CTL1&ADC12BUSY) count++;
374   return count;
375 }
void write_analog_mux (unsigned char)
Definition at line 377 of file ueaclib.c.
Referenced by timer_a0_irq().
377                                             {
378   select&=0x07;   // clamp the input to 7 
379   select<<=4;     // shift to align with bits 6-4 (mux select bits)
380   P4OUT&=0x8F;    // clear the mux select bits
381   P4OUT|=select;  // "or" in the new select value
382 }
void write_current (int, int)
Definition at line 384 of file ueaclib.c.
References dac_translation, cal::i_200uA_offset, cal::i_zero_offset, ueac::pin_cal, ueac_state, and write_dac().
Referenced by current_output_calibration(), evaluate_lla(), lla_disable(), lla_enable(), main(), print_grid_i(), scan_probes(), and ueac_execute_instruction().
384                                              {
385   if (value_uA>200) value_uA=200;
386   if (value_uA<-200) value_uA=-200;
387   if (value_uA==0) {
388     write_dac(channel,(dac_translation[200]+ueac_state.pin_cal[channel].i_zero_offset));
389   }
390   else {
391     write_dac(channel,dac_translation[200-value_uA]+ueac_state.pin_cal[channel].i_200uA_offset);
392   }
393 }
void write_dac (int, int)
Definition at line 395 of file ueaclib.c.
References send_spi_byte().
Referenced by current_output_calibration(), and write_current().
395                                       {
396   // write_dac(channel,value)
397   // channel = 0-24 where the channels are the control voltages for the current sources. The current 
398   // sources are labeled starting at the top left corner as follows.
399   //  0  1  2  3  4
400   //  5  6  7  8  9
401   // 10 11 12 13 14
402   // 15 16 17 18 19
403   // 20 21 22 23 24
404   //
405   // Value = 0-1023 (10-bit) where the number represents a control voltage that is 0-3.3v. Each bit represents 
406   // a voltage of 3.3v/1023 or 3.22mV. 
407   //
408   // Hardware Note: Channels 0-23 are implemented by external SPI octal dacs (Linear LTC1660 components). Channel 
409   // 24 is implemented using DAC0 on the MSP430 
410   // 
411   // Initial Version BH 11/1/05
412 
413   if (channel < 8) {
414     P4OUT&=~0x01;                                   // assert the proper chip select
415     channel++;                                      // increment the channel number LTC1660 channels run from 1-8   
416   }           
417   else if (channel < 16) {
418     P4OUT&=~0x02;                                   // assert the proper chip select
419     channel-=7;                                     // bring channel number into range 1-8
420   } 
421   else if (channel < 24) {
422     P4OUT&=~0x04;                                   // assert the proper chip select
423     channel-=15;                                    // bring channel number into range 1-8
424   }
425   else if (channel == 24) {
426     DAC12_0DAT=value<<2;                            // Shift up to a 12-bit number and write to the MSP430 DAC0 
427     return;                                         // This is all to do for the MSP430 DAC case, exit...
428   }
429   else {                                            // channel number provided is too large, exit... 
430     return;
431   }
432   value=(value&0x03FF)<<2;                          // mask and shift the value to align properly in the dac sentence
433   channel<<=4;
434   *(((unsigned char *) &value)+1)|=((unsigned char) channel); // "or" in the channel number to the value data
435   send_spi_byte(*(((unsigned char *) &value)+1));             // send the high byte 
436   send_spi_byte(*((unsigned char *) &value));                 // send the high byte 
437   P4OUT|=0x0F;                                                // deassert all of the spi dac chip selects   
438 }
void write_led (int, int)
Definition at line 497 of file ueaclib.c.
Referenced by current_output_calibration(), main(), and scan_leds().
497                                          {
498   static unsigned long led_state = 0x00000000;
499   if (enable) {
500     if (channel<8) {
501       *((unsigned char *) &led_state) |= 0x01<<channel;       // Save the new state of the LED in led_state
502       P1OUT=*((unsigned char *) &led_state);                  // Place the relevant byte of led_state on the latch bus 
503       P5OUT|=0x01;                                            // strobe the chip select for the target latch
504       P5OUT&=~0x01;                                           // clear the chip select bit
505     }
506     else if (channel<16) {
507       channel-=8;
508       *(((unsigned char *) &led_state)+1) |= 0x01<<channel;  
509       P1OUT=*(((unsigned char *) &led_state)+1);  
510       P5OUT=0x02;
511       P5OUT&=~0x02;                                           // clear the chip select bit
512     }
513     else if (channel<24) {
514       channel-=16;
515       *(((unsigned char *) &led_state)+2) |= 0x01<<channel;  
516       P1OUT=*(((unsigned char *) &led_state)+2);  
517       P5OUT=0x04;
518       P5OUT&=~0x04;                                           // clear the chip select bit
519     }
520     else if (channel==24) {
521       *(((unsigned char *) &led_state)+3) |= 0x01;  
522       P2OUT|=0x01;
523     }
524   }
525   else {
526     if (channel<8) {
527       *((unsigned char *) &led_state) &= ~(0x01<<channel);  
528       P1OUT=*((unsigned char *) &led_state);  
529       P5OUT=0x01;
530       P5OUT&=~0x01;                                           // clear the chip select bit
531     }
532     else if (channel<16) {
533       channel-=8;
534       *(((unsigned char *) &led_state)+1) &= ~(0x01<<channel);  
535       P1OUT=*(((unsigned char *) &led_state)+1);  
536       P5OUT=0x02;
537       P5OUT&=~0x02;                                           // clear the chip select bit
538     }
539     else if (channel<24) {
540       channel-=16;
541       *(((unsigned char *) &led_state)+2) &= ~(0x01<<channel);  
542       P1OUT=*(((unsigned char *) &led_state)+2);  
543       P5OUT=0x04;
544       P5OUT&=~0x04;                                           // clear the chip select bit
545     }
546     else if (channel==24) {
547       *(((unsigned char *) &led_state)+3) &= 0xFE;  
548       P2OUT&=0xFE;
549     }
550   }
551 }
void write_lla (int, int)
Definition at line 553 of file ueaclib.c.
Referenced by current_output_calibration(), lla_add(), lla_disable(), lla_enable(), main(), print_grid_i(), and scan_probes().
553                                          {
554   static unsigned long lla_state = 0x00000000;
555   if (enable) {
556     if (channel<8) {
557       *((unsigned char *) &lla_state) |= 0x01<<channel;       // Save the new state of the LED in lla_state
558       P1OUT=*((unsigned char *) &lla_state);                  // Place the relevant byte of lla_state on the latch bus 
559       P5OUT|=0x08;                                            // strobe the chip select for the target latch
560       P5OUT&=~0x08;                                           // clear the chip select bit
561     }
562     else if (channel<16) {
563       channel-=8;
564       *(((unsigned char *) &lla_state)+1) |= 0x01<<channel;  
565       P1OUT=*(((unsigned char *) &lla_state)+1);  
566       P5OUT=0x10;
567       P5OUT&=~0x10;                                           // clear the chip select bit
568     }
569     else if (channel<24) {
570       channel-=16;
571       *(((unsigned char *) &lla_state)+2) |= 0x01<<channel;  
572       P1OUT=*(((unsigned char *) &lla_state)+2);  
573       P5OUT=0x20;
574       P5OUT&=~0x20;                                           // clear the chip select bit
575     }
576     else if (channel==24) {
577       *(((unsigned char *) &lla_state)+3) |= 0x01;  
578       P2OUT|=0x02;
579     }
580   }
581   else {
582     if (channel<8) {
583       *((unsigned char *) &lla_state) &= ~(0x01<<channel);  
584       P1OUT=*((unsigned char *) &lla_state);  
585       P5OUT=0x08;
586       P5OUT&=~0x08;                                           // clear the chip select bit
587     }
588     else if (channel<16) {
589       channel-=8;
590       *(((unsigned char *) &lla_state)+1) &= ~(0x01<<channel);  
591       P1OUT=*(((unsigned char *) &lla_state)+1);  
592       P5OUT=0x10;
593       P5OUT&=~0x10;                                           // clear the chip select bit
594     }
595     else if (channel<24) {
596       channel-=16;
597       *(((unsigned char *) &lla_state)+2) &= ~(0x01<<channel);  
598       P1OUT=*(((unsigned char *) &lla_state)+2);  
599       P5OUT=0x20;
600       P5OUT&=~0x20;                                           // clear the chip select bit
601     }
602     else if (channel==24) {
603       *(((unsigned char *) &lla_state)+3) &= 0xFE;  
604       P2OUT&=0xFD;
605     }
606   }
607 }