all: runit

runit:
	./function_gen

plot: 
	gnuplot ./dat/1.cmd
	gnuplot ./dat/2.cmd
	gnuplot ./dat/3.cmd
	gnuplot ./dat/4.cmd
	gnuplot ./dat/5.cmd
	gnuplot ./dat/6.cmd
	gnuplot ./dat/7.cmd
	gnuplot ./dat/8.cmd
	gnuplot ./dat/9.cmd
	gnuplot ./dat/10.cmd
	gnuplot ./dat/11.cmd
	gnuplot ./dat/12.cmd
	gnuplot ./dat/13.cmd
	gnuplot ./dat/14.cmd
	gnuplot ./dat/15.cmd
	gnuplot ./dat/16.cmd
	gnuplot ./dat/17.cmd
	gnuplot ./dat/18.cmd
	gnuplot ./dat/19.cmd
	gnuplot ./dat/20.cmd
	gnuplot ./dat/21.cmd
	gnuplot ./dat/22.cmd
	gnuplot ./dat/23.cmd
	gnuplot ./dat/24.cmd
	gnuplot ./dat/25.cmd
	gnuplot ./dat/26.cmd
	gnuplot ./dat/27.cmd

view:
	xv ./dat/1.jpg
	xv ./dat/2.jpg
	xv ./dat/3.jpg
	xv ./dat/4.jpg
	xv ./dat/5.jpg
	xv ./dat/6.jpg
	xv ./dat/7.jpg
	xv ./dat/8.jpg
	xv ./dat/9.jpg
	xv ./dat/10.jpg
	xv ./dat/11.jpg
	xv ./dat/12.jpg
	xv ./dat/13.jpg
	xv ./dat/14.jpg
	xv ./dat/15.jpg
	xv ./dat/16.jpg
	xv ./dat/17.jpg
	xv ./dat/18.jpg
	xv ./dat/19.jpg
	xv ./dat/20.jpg
	xv ./dat/21.jpg	
	xv ./dat/22.jpg
	xv ./dat/23.jpg
	xv ./dat/24.jpg
	xv ./dat/25.jpg
	xv ./dat/26.jpg
	xv ./dat/27.jpg

clean:
	rm ./dat/*.cmd
	rm ./dat/*.jpg
	rm ./dat/*.dat
