#!/usr/bin/perl -w

print ("const unsigned short a2d_i_conversion[]={ \\\n  ");
$row=0;
for ($i=0;$i<4096;$i++) {
    printf("%d",((3.3*2215)*$i*1000)/(4096*715*11));
    if ($i!=4095) {
        printf(",");
    }
    if ($row++>=9) {
        printf(" \\\n  ");
        $row=0;
    }
}
print ("};\n");

